server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456

#
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true

#H2控制台:http://localhost:8081/h2-console
  h2:
    console:
      path: /h2-console
      enabled: true



